mysql:
  userName: "root"
  password: "P@7z#L&2*K!W8%X"
  ip: "123.60.188.152"
  port: 3306
  dbName: "imchat"

redis:
  ip: "123.60.188.152"
  port: 6379
  password: "F!9@L#4&X%7q*P6"
  DB: 0
  poolSize: 30
  minIdleConn: 30

oss:
  Endpoint: "oss-cn-hangzhou.aliyuncs.com"
  AccessKeyId: "LTAI5tNCXPJwS3MstKoKgixh"
  AccessKeySecret: "YhHE8OyCMsqfjwOnxQ1oO7paYlDjVHX"
  Bucket: "ginchat"

timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间   
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线 
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H

port:
  server: 8280
  udp: 3001
