// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Communities *communities
	Contacts    *contacts
	Messages    *messages
	UserGroups  *userGroups
	Users       *users
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Communities = &Q.Communities
	Contacts = &Q.Contacts
	Messages = &Q.Messages
	UserGroups = &Q.UserGroups
	Users = &Q.Users
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Communities: newCommunities(db, opts...),
		Contacts:    newContacts(db, opts...),
		Messages:    newMessages(db, opts...),
		UserGroups:  newUserGroups(db, opts...),
		Users:       newUsers(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Communities communities
	Contacts    contacts
	Messages    messages
	UserGroups  userGroups
	Users       users
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Communities: q.Communities.clone(db),
		Contacts:    q.Contacts.clone(db),
		Messages:    q.Messages.clone(db),
		UserGroups:  q.UserGroups.clone(db),
		Users:       q.Users.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Communities: q.Communities.replaceDB(db),
		Contacts:    q.Contacts.replaceDB(db),
		Messages:    q.Messages.replaceDB(db),
		UserGroups:  q.UserGroups.replaceDB(db),
		Users:       q.Users.replaceDB(db),
	}
}

type queryCtx struct {
	Communities ICommunitiesDo
	Contacts    IContactsDo
	Messages    IMessagesDo
	UserGroups  IUserGroupsDo
	Users       IUsersDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Communities: q.Communities.WithContext(ctx),
		Contacts:    q.Contacts.WithContext(ctx),
		Messages:    q.Messages.WithContext(ctx),
		UserGroups:  q.UserGroups.WithContext(ctx),
		Users:       q.Users.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
