// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAnswerRecords = "answer_records"

// AnswerRecords mapped from table <answer_records>
type AnswerRecords struct {
	ID            int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:答题记录ID" json:"id"`  // 答题记录ID
	ExamID        int    `gorm:"column:exam_id;not null;comment:考试ID" json:"exam_id"`               // 考试ID
	QuestionNo    int    `gorm:"column:question_no;not null;comment:题目编号" json:"question_no"`       // 题目编号
	QuestionID    int    `gorm:"column:question_id;not null;comment:题目ID" json:"question_id"`       // 题目ID
	UserAnswer    string `gorm:"column:user_answer;not null;comment:用户答案" json:"user_answer"`       // 用户答案
	CorrectAnswer string `gorm:"column:correct_answer;not null;comment:正确答案" json:"correct_answer"` // 正确答案
	IsCorrect     int    `gorm:"column:is_correct;comment:是否答对" json:"is_correct"`                  // 是否答对
}

// TableName AnswerRecords's table name
func (*AnswerRecords) TableName() string {
	return TableNameAnswerRecords
}
