// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGroupBasic = "group_basic"

// GroupBasic mapped from table <group_basic>
type GroupBasic struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string         `gorm:"column:name" json:"name"`
	OwnerID     int32          `gorm:"column:owner_id" json:"owner_id"`
	Icon        string         `gorm:"column:icon" json:"icon"`
	Type        int32          `gorm:"column:type" json:"type"`
	Description string         `gorm:"column:description" json:"description"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName GroupBasic's table name
func (*GroupBasic) TableName() string {
	return TableNameGroupBasic
}
