// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessages = "messages"

// Messages mapped from table <messages>
type Messages struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FormID      int32          `gorm:"column:form_id;not null" json:"form_id"`
	TargetID    int32          `gorm:"column:target_id;not null" json:"target_id"`
	Type        int32          `gorm:"column:type;not null" json:"type"`
	Content     string         `gorm:"column:content" json:"content"`
	Pic         string         `gorm:"column:pic" json:"pic"`
	URL         string         `gorm:"column:url" json:"url"`
	Description string         `gorm:"column:description" json:"description"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Messages's table name
func (*Messages) TableName() string {
	return TableNameMessages
}
