// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FormID      string         `gorm:"column:form_id" json:"form_id"`
	TargetID    string         `gorm:"column:target_id" json:"target_id"`
	Type        string         `gorm:"column:type" json:"type"`
	Media       int32          `gorm:"column:media" json:"media"`
	Content     string         `gorm:"column:content" json:"content"`
	Pic         string         `gorm:"column:pic" json:"pic"`
	URL         string         `gorm:"column:url" json:"url"`
	Description string         `gorm:"column:description" json:"description"`
	Amount      int32          `gorm:"column:amount" json:"amount"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
