// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuestionOptions = "question_options"

// QuestionOptions mapped from table <question_options>
type QuestionOptions struct {
	ID         int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`      // 主键ID
	QuestionID int    `gorm:"column:question_id;not null;comment:题目ID" json:"question_id"`         // 题目ID
	OptionKey  string `gorm:"column:option_key;not null;comment:选项标识（如A、B、C、D）" json:"option_key"` // 选项标识（如A、B、C、D）
	OptionText string `gorm:"column:option_text;not null;comment:选项内容" json:"option_text"`         // 选项内容
}

// TableName QuestionOptions's table name
func (*QuestionOptions) TableName() string {
	return TableNameQuestionOptions
}
