// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserGroups = "user_groups"

// UserGroups mapped from table <user_groups>
type UserGroups struct {
	ID          int            `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	OwnerID     int            `gorm:"column:owner_id;not null" json:"owner_id"`
	Icon        string         `gorm:"column:icon" json:"icon"`
	Type        int            `gorm:"column:type;not null" json:"type"`
	Description string         `gorm:"column:description" json:"description"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserGroups's table name
func (*UserGroups) TableName() string {
	return TableNameUserGroups
}
