// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUsers = "users"

// Users mapped from table <users>
type Users struct {
	ID            int            `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserCode      string         `gorm:"column:user_code;not null" json:"user_code"`
	Name          string         `gorm:"column:name;not null" json:"name"`
	Password      string         `gorm:"column:password;not null" json:"password"`
	Salt          string         `gorm:"column:salt" json:"salt"`
	Phone         string         `gorm:"column:phone;not null" json:"phone"`
	Email         string         `gorm:"column:email;not null" json:"email"`
	Avatar        string         `gorm:"column:avatar" json:"avatar"`
	LoginTime     time.Time      `gorm:"column:login_time" json:"login_time"`
	HeartbeatTime time.Time      `gorm:"column:heartbeat_time" json:"heartbeat_time"`
	CreatedAt     time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Users's table name
func (*Users) TableName() string {
	return TableNameUsers
}
